### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/merged.js'

### ISSUE THREAD

**Issue by PeterParker369** [dpnishant/appmon#101]
I'm executing:
`python appmon.py -a com.example.test --spawn 1 -p android -s scripts/Android -o d:/app_mon_dumps -r dump.db`

It gives me an error:
```
[32mNow Spawning com.example.test[0m
[33m[INFO] Attached to com.example.test[0m
[31m[ERROR] [Errno 2] No such file or directory: '/tmp/merged.js'[0m
Traceback (most recent call last):
  File "appmon.py", line 361, in <module>
    script = session.create_script(generate_injection())
  File "appmon.py", line 194, in generate_injection
    with codecs.open(merge_scripts(script_path), 'r', 'utf-8') as f:
  File "appmon.py", line 143, in merge_scripts
    with codecs.open(merged_script_path, "w", "utf-8") as f:
  File "C:\Users\........................\Python37\lib\codecs.py", line 904, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/merged.js'
```

I found same error at [](https://github.com/dpnishant/appmon/issues/43).
It was solved by adding to PATH:
`merge_script_path = ‘C:/Users/<nombre_usuario>/AppData/Local/Temp/merged.js’`

But it doesn't helped. Please help, what should I do?

**Comment by PeterParker369** [comment]
Everything is works FINE! I'm stupid :)
