### ISSUE TITLE
[ERROR] unable to connect to remote frida-server: closed

### ISSUE THREAD

**Issue by m0hamedessam** [dpnishant/appmon#106]
i did everything but when i connect phone i got 

[ERROR] unable to connect to remote frida-server: closed

im using Ubuntu 14 on virtual box

any advice ??

**Comment by m0hamedessam** [comment]
any advice ????

**Comment by m0hamedessam** [comment]
i figure out i had to open app but anyway app crash :(

**Comment by dpnishant** [comment]
Sorry to know that. You can check ADB logs using logcat or similar to know the exact reason of the crash. Do let let us know.

**Comment by m0hamedessam** [comment]
i will try and let you know but anyway i face problem on script


[Aug 20 2020 11:34 AM] Dumped to ./app_dumps/Gadget.db
'id' is not a valid column name.
{u'method': u'chmod', u'artifact': [{u'name': u'Pathname', u'value': u'/data/data/com.ngc.FastTvLitePlus/shared_prefs/com.google.android.gms.measurement.prefs.xml', u'argSeq': 1}, {u'name': u'Mode', u'value': 432, u'argSeq': 2}, {u'name': u'Status', u'value': u'Success', u'argSeq': 0}], u'txnType': u'syscall', u'lib': u'libc.so', u'time': u'2020-08-20T08:34:38.477Z'}

any idea whats problem on script not write on database ??

**Comment by m0hamedessam** [comment]
08-20 12:08:39.177   878  2101 D ActivityManager: startService callerProcessName:com.google.android.gms, calleePkgName: com.google.android.gms
08-20 12:08:39.277  7725  7725 W System.err: java.security.InvalidParameterException
08-20 12:08:39.287  7725  7725 W System.err: 	at com.ngc.TVLite.c0.c.a()
08-20 12:08:39.287  7725  7725 W System.err: 	at com.ngc.TVLite.LauncherActivity.a()
08-20 12:08:39.287  7725  7725 W System.err: 	at com.ngc.TVLite.LauncherActivity.a()
08-20 12:08:39.287  7725  7725 W System.err: 	at com.ngc.TVLite.d.a(lambda)
08-20 12:08:39.287  7725  7725 W System.err: 	at c.e.a.c.f.s.run()
08-20 12:08:39.287  7725  7725 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
08-20 12:08:39.287  7725  7725 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-20 12:08:39.287  7725  7725 W System.err: 	at android.os.Looper.loop(Looper.java:145)
08-20 12:08:39.287  7725  7725 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5951)
08-20 12:08:39.287  7725  7725 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-20 12:08:39.287  7725  7725 W System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
08-20 12:08:39.287  7725  7725 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
08-20 12:08:39.287  7725  7725 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)


i think problem app request location and open gps any idea to bypass it on splash activity  ??

**Comment by salman0ansari** [comment]
same error any fix?
