### ISSUE TITLE
NameError: name 'dev_identity' is not defined

### ISSUE THREAD

**Issue by marcelocecin** [dpnishant/appmon#39]
[+] Unpacking IPA...
[+] Injecting DYLIB...
[+] Code-signing...
/tmp/appmon_ipa/SinespCidadao/Payload/SinespCidadao.app/FridaGadget.dylib: replacing existing signature
/tmp/appmon_ipa/SinespCidadao/Payload/SinespCidadao.app: replacing existing signature
Traceback (most recent call last):
  File "./ipa_installer.py", line 167, in <module>
    subprocess.check_output(["node", iparesign_path, "--without-watchapp", "--identity", dev_identity, "--mobileprovision", mobileprovision_path, injected_ipa_filename])
NameError: name 'dev_identity' is not defined

**Comment by dpnishant** [comment]
Follow every instruction mention here: https://github.com/dpnishant/appmon/wiki/8.-Usage-Guide:-AppMon-IPA-Installer and then try to re-run

**Comment by dpnishant** [comment]
Fixed with f39ef41. Please reopen if issue still persists

**Comment by marcelocecin** [comment]
[+] Trying to detect device...
[+] Found (D111AP, iPhone 7 Plus, iphoneos, arm64) a.k.a. 'iPhone' connected through USB.
[+] Unpacking IPA...
Traceback (most recent call last):
  File "ipa_installer.py", line 161, in <module>
    executable_filepath = getMachOExecutable(app_path)
  File "ipa_installer.py", line 91, in getMachOExecutable
    plist = plistlib.readPlist(plist_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 8

**Comment by dpnishant** [comment]
Fixed in 4b58c83. Please reopen if issue still persists

**Comment by marcelocecin** [comment]
[+] Trying to detect device...
[+] Found (D111AP, iPhone 7 Plus, iphoneos, arm64) a.k.a. 'iPhone' connected through USB.
[+] Unpacking IPA...
[+] Injecting DYLIB...
[+] Code-signing...
/tmp/appmon_ipa/SinespCidadao/Payload/SinespCidadao.app/FridaGadget.dylib: replacing existing signature
/tmp/appmon_ipa/SinespCidadao/Payload/SinespCidadao.app: replacing existing signature
Error: ipa is encrypted
    at ApplesignSession.signAppDirectory (/Users/marcelocecin/Downloads/appmon/ipa_installer/node-applesign/session.js:120:21)
    at unzip (/Users/marcelocecin/Downloads/appmon/ipa_installer/node-applesign/session.js:79:12)
    at tools.unzip (/Users/marcelocecin/Downloads/appmon/ipa_installer/node-applesign/session.js:366:11)
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
Traceback (most recent call last):
  File "ipa_installer.py", line 179, in <module>
    subprocess.check_output(["node", iparesign_path, "--without-watchapp", "--identity", dev_identity, "--mobileprovision", mobileprovision_path, injected_ipa_filename])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['node', 'node-applesign/bin/ipa-resign.js', '--without-watchapp', '--identity', 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXD6', '--mobileprovision', '/Users/marcelocecin/Library/Developer/Xcode/DerivedData/hello-cpyjxdwswhorswgvsxbzcjsdyfpj/Build/Products/Debug-iphoneos/hello.app/embedded.mobileprovision', 'SinespCidadao-injected.ipa']' returned non-zero exit status 1
