### ISSUE TITLE
No such file or directory: 'tmp/merged.js'

### ISSUE THREAD

**Issue by adefirmant** [dpnishant/appmon#43]
Please help, i cannot solve this issue : " No such file or directory: 'tmp/merged.js' "

C:\AppMon>py -2 appmon.py -a "com.app.myapp" -p android -s scripts/Android

     ___      .______   .______   .___  ___.   ______   .__   __.
    /   \     |   _  \  |   _  \  |   \/   |  /  __  \  |  \ |  |
   /  ^  \    |  |_)  | |  |_)  | |  \  /  | |  |  |  | |   \|  |
  /  /_\  \   |   ___/  |   ___/  |  |\/|  | |  |  |  | |  . `  |
 /  _____  \  |  |      |  |      |  |  |  | |  `--'  | |  |\   |
/__/     \__\ | _|      | _|      |__|  |__|  \______/  |__| \__|
                        github.com/dpnishant

←[33m[INFO] Attached to com.app.myapp←[0m
←[31m[ERROR] [Errno 2] No such file or directory: '/tmp/merged.js'←[0m
Traceback (most recent call last):
  File "appmon.py", line 341, in <module>
    script = session.create_script(generate_injection())
  File "appmon.py", line 180, in generate_injection
    with codecs.open(merge_scripts(script_path), 'r', 'utf-8') as f:
  File "appmon.py", line 135, in merge_scripts
    with codecs.open(merged_script_path, "w", "utf-8") as f:
  File "C:\Python27\lib\codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/tmp/merged.js'

Please help,

**Comment by adefirmant** [comment]
Sorry, i have solved this issue by changing merged.js directory to Temp windows directory 

source: https://www.welivesecurity.com/2016/11/07/apk-analysis-using-appmon/
