### ISSUE TITLE
Frida-ps and frida-trace works, but appmon fails both to attach or spwan process.

### ISSUE THREAD

**Issue by strlbs** [dpnishant/appmon#46]
Hi @dpnishant and team,

I'm new to Frida and found by accident this nice project called Appmon. My mobile is Samsung Neo III with supersu and all works fine. I downloaded and installed frida and both frida-ps -U and frida-trace works with my target process.

However, when I try with appmon if fails as demonstrated below:

```
$ python appmon.py -a "com.MyTest.android" -p android --spawn 1

     ___      .______   .______   .___  ___.   ______   .__   __. 
    /   \     |   _  \  |   _  \  |   \/   |  /  __  \  |  \ |  | 
   /  ^  \    |  |_)  | |  |_)  | |  \  /  | |  |  |  | |   \|  | 
  /  /_\  \   |   ___/  |   ___/  |  |\/|  | |  |  |  | |  . `  | 
 /  _____  \  |  |      |  |      |  |  |  | |  `--'  | |  |\   | 
/__/     \__\ | _|      | _|      |__|  |__|  \______/  |__| \__| 
                        github.com/dpnishant
                                                                  

Now Spawning com.MyTest.android
[INFO] Attached to com.MyTest.android
[INFO] Building injection...
[ERROR] session is detached
Traceback (most recent call last):
  File "appmon.py", line 341, in <module>
    script = session.create_script(generate_injection())
  File "/Library/Python/2.7/site-packages/frida/core.py", line 182, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
InvalidOperationError: session is detached

```

```
$ python appmon.py -a "com.MyTest.android" -p android --spawn 0

     ___      .______   .______   .___  ___.   ______   .__   __. 
    /   \     |   _  \  |   _  \  |   \/   |  /  __  \  |  \ |  | 
   /  ^  \    |  |_)  | |  |_)  | |  \  /  | |  |  |  | |   \|  | 
  /  /_\  \   |   ___/  |   ___/  |  |\/|  | |  |  |  | |  . `  | 
 /  _____  \  |  |      |  |      |  |  |  | |  `--'  | |  |\   | 
/__/     \__\ | _|      | _|      |__|  |__|  \______/  |__| \__| 
                        github.com/dpnishant
                                                                  

[INFO] Attached to com.MyTest.android
[INFO] Building injection...
[INFO] Instrumentation started...
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Aug/2017 22:40:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2017 22:40:25] "GET /static/img/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [19/Aug/2017 22:40:38] "GET /monitor?app= HTTP/1.1" 301 -
127.0.0.1 - - [19/Aug/2017 22:40:38] "GET /monitor/?app= HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2017 22:40:39] "GET /static/img/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [19/Aug/2017 22:40:39] "GET /static/img/to-bottom.png HTTP/1.1" 304 -
127.0.0.1 - - [19/Aug/2017 22:40:39] "GET /static/img/to-top.png HTTP/1.1" 304 -
[2017-08-19 22:40:39,513] ERROR in app: Exception on /api/fetch [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appmon.py", line 59, in serve_json
    response = db.read_from_database(db_name, index)
  File "/Users/strlbs/Downloads/MyTest/appmon/database/__init__.py", line 50, in read_from_database
    db = dataset.connect('sqlite:///./app_dumps/%s.db' % (db_path))
  File "/Library/Python/2.7/site-packages/dataset/__init__.py", line 42, in connect
    ensure_schema=ensure_schema, row_type=row_type)
  File "/Library/Python/2.7/site-packages/dataset/persistence/database.py", line 62, in __init__
    self.metadata.reflect(self.engine, views=reflect_views)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/schema.py", line 3855, in reflect
    with bind.connect() as conn:
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 2091, in connect
    return self._connection_cls(self, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 2177, in raw_connection
    self.pool.unique_connection, _connection)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 328, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 1292, in _do_get
    return self.connection
  File "/Library/Python/2.7/site-packages/sqlalchemy/util/langhelpers.py", line 764, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 1264, in connection
    return _ConnectionRecord(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/Library/Python/2.7/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
OperationalError: (sqlite3.OperationalError) unable to open database file
127.0.0.1 - - [19/Aug/2017 22:40:39] "GET /api/fetch?id=0&app=&_=1503193239398 HTTP/1.1" 500 -
127.0.0.1 - - [19/Aug/2017 22:40:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2017 22:40:50] "GET /static/img/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [19/Aug/2017 22:40:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2017 22:40:50] "GET /static/img/logo.png HTTP/1.1" 304 -
127.0.0.1 - - [19/Aug/2017 22:41:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Aug/2017 22:41:25] "GET /static/img/logo.png HTTP/1.1" 304 -
```

The second one appears to work, but if I go to the website (http://127.0.0.1:5000) no process appears (I can write MyTest) just the beginning, just the end and nothing appears, so the only solution is "next" without a target proxy. Consequently it displays an error and nothing is showed.

I'm using Mac (if it makes any difference).  AppMon Sniffer v0.1, Nishant Das Patnaik, 2016

Thanks.

**Comment by dpnishant** [comment]
This might help: https://stackoverflow.com/questions/4636970/sqlite3-operationalerror-unable-to-open-database-file
