### ISSUE TITLE
No handlers could be found for logger "sqlalchemy.pool.StaticPool"

### ISSUE THREAD

**Issue by stayliv3** [dpnishant/appmon#60]
the newest frida version 10.6.18

AttributeError: 'int' object has no attribute 'replace' error

No handlers could be found for logger "sqlalchemy.pool.StaticPool"
[2017-10-27 04:39:52,012] ERROR in app: Exception on /api/fetch [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appmon.py", line 64, in serve_json
    response = db.read_from_database(db_name, index)
  File "/root/appmon/database/__init__.py", line 67, in read_from_database
    artifact_value = artifact_value.replace("<", "&lt;").replace(">", "&gt;")
AttributeError: 'int' object has no attribute 'replace'
127.0.0.1 - - [27/Oct/2017 04:39:52] "GET /api/fetch?id=0&app=com.zywawa.claw&_=1509093591702 HTTP/1.1" 500 -

500error   if you need ,i can upload the android app.   or you can download it from  http://a.attach.diaoyu-3.com/zywawa.apk?1509094220305

**Comment by dpnishant** [comment]
This is fixed in Pull #59
