### ISSUE TITLE
Could not smali file

### ISSUE THREAD

**Issue by davidsarkany** [dpnishant/appmon#80]
**System**
Ubuntu 18.04.1 LTS
[scan.apk](https://github.com/dpnishant/appmon/files/2384931/scan.zip)

`python apk_builder.py --apk /home/david/scan.apk`

```
[I] Preparing work directory...
[I] Expanding APK...
[I] Searching .smali
[I] Patching .smali
[I] Injecting libs
[I] Building APK
../../../../../tmp/appmon_apk/org.a4_mobile.scanshop/smali/org/a4_mobile/scanshop/MainActivity.smali[107,4] missing END_METHOD_DIRECTIVE at '.method'
../../../../../tmp/appmon_apk/org.a4_mobile.scanshop/smali/org/a4_mobile/scanshop/MainActivity.smali[118,4] missing EOF at '.locals'
Could not smali file: org/a4_mobile/scanshop/MainActivity.smali
Traceback (most recent call last):
  File "apk_builder.py", line 176, in <module>
    build_apk_output = subprocess.check_output(["apktool", "build", os.path.join(WORK_DIR, package_name)])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['apktool', 'build', '/tmp/appmon_apk/org.a4_mobile.scanshop']' returned non-zero exit status 1
```

**Comment by AxDSan** [comment]
Same thing here...

**Comment by AJBrewer** [comment]
This is likely because, as of version 2.1.0 of apktool, reversing into smali is not done in apktool. See the following on the apktool website:

"Smali Debugging (Removed in 2.1.0 in favor of IdeaSmali)" 

Feasibly, it may be possible to download an older version of apktool and have appmon use that instead of any new versions that dont have baksmalling capabilities
