### ISSUE TITLE
CalledProcessError: Command '['apktool', 'build', '/tmp/appmon_apk/com.example']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by r3v3rs3-D** [dpnishant/appmon#97]
After looking up this problem, they say it has to do with apktool, I'm not sure but any help would be appreciated. 

This the stack trace: 
```
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 15, --target-sdk-version, 29, --version-code, 453123, --version-name, 2.19.360, --no-version-vectors, -F, /tmp/APKTOOL17456569574128681174.tmp, -0, arsc, -0, png, -0, wav, -0, m4a, -0, mp4, -0, arsc, -I, /home/opus/.local/share/apktool/framework/1.apk, -S, /tmp/appmon_apk/com.example/res, -M, /tmp/appmon_apk/com.example/AndroidManifest.xml]
Traceback (most recent call last):
  File "apk_builder.py", line 176, in <module>
    build_apk_output = subprocess.check_output(["apktool", "build", os.path.join(WORK_DIR, package_name)])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['apktool', 'build', '/tmp/appmon_apk/com.example']' returned non-zero exit status 1
```

**Comment by dpnishant** [comment]
Seems the same to me too.

**Comment by r3v3rs3-D** [comment]
@dpnishant is there a way to integrate this temporary solution? https://github.com/iBotPeaches/Apktool/issues/1880

**Comment by nanpuhaha** [comment]
same here.

```
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/fz/bk91_ksx0sbfll3tjq32rc1c0000gn/T/brut_util_Jar_116438534712133790824894208157382643086.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 30, --version-code, 3080, --version-name, 3.3.00, --no-version-vectors, -F, /var/folders/fz/bk91_ksx0sbfll3tjq32rc1c0000gn/T/APKTOOL18324079989942587749.tmp, -e, /var/folders/fz/bk91_ksx0sbfll3tjq32rc1c0000gn/T/APKTOOL7188363647459584557.tmp, -0, arsc, -I, /Users/username/Library/apktool/framework/1.apk, -S, /tmp/appmon_apk/com.example.app/res, -M, /tmp/appmon_apk/com.example.app/AndroidManifest.xml]
Traceback (most recent call last):
  File "/Users/username/Desktop/GitHub/appmon/apk_builder/apk_builder.py", line 178, in <module>
    build_apk_output = subprocess.check_output(["apktool", "build", os.path.join(WORK_DIR, package_name)])
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['apktool', 'build', '/tmp/appmon_apk/com.example.app']' returned non-zero exit status 1.
```
