### ISSUE TITLE
64 bit emulator returns: unable to handle 64-bit processes due to build configuration

### ISSUE THREAD

**Issue by hazcod** [dpnishant/appmon#98]
Any idea how I can use the 64 bit version of frida (server/gadget) on an unrooted emulator?
I've seen other issues about this but never with a solution.

Instructions:
```
export PATH="/Users/xxx/Library/Android/sdk/build-tools/28.0.3:$PATH"
python apk_builder.py --apk ~/Desktop/app.apk
python appmon.py -p android -a app -s scripts/Android
[ERROR] unable to handle 64-bit processes due to build configuration
Traceback (most recent call last):
  File "appmon.py", line 353, in init_session
    session = device.attach(arg_to_attach)
  File "/usr/local/lib/python2.7/site-packages/frida/core.py", line 110, in attach
    return Session(self._impl.attach(self._pid_of(target)))
NotSupportedError: unable to handle 64-bit processes due to build configuration
```

**Comment by hazcod** [comment]
Was running  bad version of `frida-server`.
