### ISSUE TITLE
urllib.parse error

### ISSUE THREAD

**Issue by metafalo** [dpnishant/appmon#99]
Hi. I am trying to install appmon following the guides in github and searching around but i allways get this message:

> Traceback (most recent call last):
>   File "appmon.py", line 22, in <module>
>     import database as db
>   File "/home/mf/Tools/appmon/appmon/database/__init__.py", line 18, in <module>
>     import dataset, json, time
>   File "/home/mf/Tools/appmon/local/lib/python2.7/site-packages/dataset/__init__.py", line 3, in <module>
>     from dataset.database import Database
>   File "/home/mf/Tools/appmon/local/lib/python2.7/site-packages/dataset/database.py", line 3, in <module>
>     from urllib.parse import parse_qs, urlparse
> ImportError: No module named parse
> 

I am installing it in a fresh kali machine.

**Comment by metafalo** [comment]
Solved the problem installing dataset==1.1.2
